"""The screen registry, read-only, for the system prompt (screen titles), the
fake mode (`go to ...`) and the eval script. Source of truth is
config/manifest.json (generated by the actions builder from docs/05); until it
exists, the screen tables in docs/05-action-manifest.md are parsed instead."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

from common.config import ROOT

MANIFEST_FILE = ROOT / "config" / "manifest.json"
MANIFEST_DOC = ROOT / "docs" / "05-action-manifest.md"


@dataclass(frozen=True)
class Screen:
    id: str
    url: str
    title: str
    description: str

    @property
    def parameterized(self) -> bool:
        return "{" in self.url


@dataclass(frozen=True)
class Action:
    name: str
    endpoint: str
    parameters: str
    confirm: str


def _first(d: dict[str, Any], *keys: str, default: str = "") -> str:
    for key in keys:
        value = d.get(key)
        if isinstance(value, str) and value:
            return value
    return default


def _from_json(data: Any) -> tuple[list[Screen], list[Action]]:
    screens: list[Screen] = []
    actions: list[Action] = []
    raw_screens = data.get("screens", []) if isinstance(data, dict) else []
    if isinstance(raw_screens, dict):
        raw_screens = [{"id": k, **v} for k, v in raw_screens.items() if isinstance(v, dict)]
    for s in raw_screens:
        if not isinstance(s, dict):
            continue
        sid = _first(s, "id", "screen", "name")
        url = _first(s, "url", "path", "canonical_url")
        if sid and url:
            screens.append(Screen(sid, url, _first(s, "title", default=sid), _first(s, "description", "when", "when_user_wants")))
    raw_actions = data.get("actions", []) if isinstance(data, dict) else []
    if isinstance(raw_actions, dict):
        raw_actions = [{"name": k, **v} for k, v in raw_actions.items() if isinstance(v, dict)]
    for a in raw_actions:
        if not isinstance(a, dict):
            continue
        name = _first(a, "name", "id", "tool")
        if not name:
            continue
        params = a.get("parameters", a.get("params", ""))
        if isinstance(params, (dict, list)):
            params = ", ".join(params.keys() if isinstance(params, dict) else [p if isinstance(p, str) else str(p.get("name", "")) for p in params])
        confirm = a.get("confirm", "")
        actions.append(Action(name, _first(a, "endpoint", "url"), str(params), str(confirm)))
    return screens, actions


def _cells(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def _ticks(text: str) -> list[str]:
    return re.findall(r"`([^`]+)`", text)


def _from_doc(text: str) -> tuple[list[Screen], list[Action]]:
    screens: list[Screen] = []
    actions: list[Action] = []
    section = ""
    for line in text.splitlines():
        if line.startswith("## "):
            section = line[3:].strip().lower()
            continue
        if not line.startswith("|") or set(line.replace("|", "").strip()) <= {"-", " "}:
            continue
        cells = _cells(line)
        if section == "screen registry" and len(cells) >= 4 and cells[0].startswith("`"):
            ids, urls = _ticks(cells[0]), _ticks(cells[1])
            for i, sid in enumerate(ids):
                url = urls[min(i, len(urls) - 1)] if urls else ""
                if url:
                    screens.append(Screen(sid, url, cells[2], cells[3]))
        elif section == "action registry" and len(cells) >= 5 and cells[0].startswith("`"):
            for name in _ticks(cells[0]):
                if name.startswith("_"):
                    # "packaging_config_create / _update" shorthand
                    base = _ticks(cells[0])[0].rsplit("_", 1)[0]
                    name = base + name
                actions.append(Action(name, cells[1], cells[2], cells[4] if len(cells) > 4 else ""))
    return screens, actions


@lru_cache(maxsize=1)
def load() -> tuple[tuple[Screen, ...], tuple[Action, ...], str]:
    """(screens, actions, source) — source names the file the registry came from."""
    if MANIFEST_FILE.is_file():
        try:
            screens, actions = _from_json(json.loads(MANIFEST_FILE.read_text()))
            if screens:
                return tuple(screens), tuple(actions), str(MANIFEST_FILE)
        except (OSError, ValueError):
            pass
    if MANIFEST_DOC.is_file():
        screens, actions = _from_doc(MANIFEST_DOC.read_text())
        return tuple(screens), tuple(actions), str(MANIFEST_DOC)
    return (), (), "none"


def screens() -> tuple[Screen, ...]:
    return load()[0]


def actions() -> tuple[Action, ...]:
    return load()[1]


def screen_by_id(screen_id: str | None) -> Screen | None:
    if not screen_id:
        return None
    return next((s for s in screens() if s.id == screen_id), None)


_STOP = {"the", "a", "an", "to", "go", "open", "show", "me", "take", "screen", "page", "please", "navigate", "um", "uh", "of", "my", "list"}


def _words(text: str) -> set[str]:
    words = set(re.findall(r"[a-z0-9]+", text.lower())) - _STOP
    # crude singularization so "lots" matches "lot" and vice versa
    return words | {w[:-1] for w in words if w.endswith("s") and len(w) > 3}


def match_screen(utterance: str) -> Screen | None:
    """Best non-parameterized screen for a 'go to ...' utterance (fake mode, eval)."""
    wanted = _words(utterance)
    if not wanted:
        return None
    best: tuple[float, Screen] | None = None
    for s in screens():
        if s.parameterized or s.id in ("login", "login-2fa", "password-reset"):
            continue
        title_words = _words(s.title)
        id_words = _words(s.id.replace("-", " "))
        overlap = len(wanted & (title_words | id_words))
        if not overlap:
            continue
        score = overlap * 2 + (1 if title_words <= wanted else 0) + (0.5 if s.id.endswith("-list") else 0)
        score -= 0.1 * len(title_words - wanted)
        if best is None or score > best[0]:
            best = (score, s)
    return best[1] if best else None
